# Generated by Django 2.2 on 2020-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200524_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='person.jpg', upload_to='profile_pics/'),
        ),
    ]
