# Generated by Django 2.2 on 2020-05-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200529_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default/default.jpg', upload_to='about_pics/'),
        ),
    ]
