# Generated by Django 2.2 on 2020-05-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200528_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
